/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Crear_Cuenta_paquete;
import Main_paquete.Bdd;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author HP OMEN
 */
public class Crear_Cuenta extends javax.swing.JFrame {
    boolean[] Bandera=new boolean[4];
    Crear_Cuenta_Codigo CcC = new Crear_Cuenta_Codigo();
    Bdd bdd= new Bdd();
    
    Connection conexion = null;

    public Crear_Cuenta() {
        initComponents();
        try{
            conexion=bdd.Conectar();
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JNombre = new javax.swing.JTextField();
        JContraseña1 = new javax.swing.JTextField();
        JContraseña2 = new javax.swing.JTextField();
        JGmail = new javax.swing.JTextField();
        Envio_data = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese para crear una cuenta");

        JNombre.setText("Ingrese nombre");
        JNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JNombreFocusLost(evt);
            }
        });

        JContraseña1.setText("Ingrese contraseña");
        JContraseña1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JContraseña1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JContraseña1FocusLost(evt);
            }
        });

        JContraseña2.setText("Ingrese devuelta la contraseña");
        JContraseña2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JContraseña2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JContraseña2FocusLost(evt);
            }
        });

        JGmail.setText("Ingrese el gmail");
        JGmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JGmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JGmailFocusLost(evt);
            }
        });

        Envio_data.setText("Ingresar cuenta");
        Envio_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Envio_dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Envio_data)
                            .addComponent(JNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JContraseña1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JContraseña2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(JNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(JContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(JGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(Envio_data)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JNombreFocusGained
        if (!Bandera[0]) {
            JNombre.setText("");
            Bandera[0] = true;
                } 
    }//GEN-LAST:event_JNombreFocusGained

    private void JNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JNombreFocusLost
        if(JNombre.getText().isEmpty()){
            JNombre.setText("Ingrese nombre");
            Bandera[0] = false;
        }
    }//GEN-LAST:event_JNombreFocusLost

    private void JContraseña1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JContraseña1FocusGained
        if (!Bandera[1]) {
            JContraseña1.setText("");
            Bandera[1] = true;
                } 
    }//GEN-LAST:event_JContraseña1FocusGained

    private void JContraseña1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JContraseña1FocusLost
        if(JContraseña1.getText().isEmpty()){
            JContraseña1.setText("Ingrese contraseña");
            Bandera[1] = false;
        }
    }//GEN-LAST:event_JContraseña1FocusLost

    private void JContraseña2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JContraseña2FocusGained
        if (!Bandera[2]) {
            JContraseña2.setText("");
            Bandera[2] = true;
                }
    }//GEN-LAST:event_JContraseña2FocusGained

    private void JContraseña2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JContraseña2FocusLost
       if(JContraseña2.getText().isEmpty()){
            JContraseña2.setText("Ingrese devuelta la contraseña");
            Bandera[2] = false;
        }
    }//GEN-LAST:event_JContraseña2FocusLost

    private void JGmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JGmailFocusGained
        if (!Bandera[3]) {
            JGmail.setText("");
            Bandera[3] = true;
                }
    }//GEN-LAST:event_JGmailFocusGained

    private void JGmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JGmailFocusLost
        if(JGmail.getText().isEmpty()){
            JGmail.setText("Ingrese el gmail");
            Bandera[3] = false;
        }
    }//GEN-LAST:event_JGmailFocusLost

    private void Envio_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Envio_dataActionPerformed
        String Nombre=JNombre.getText();
        
        String C1=JContraseña1.getText();
        String C2=JContraseña2.getText();
        
        String Gm=JGmail.getText();
        if(CcC.Envio_data_c(Nombre,C1,C2,Gm,conexion)){
            JOptionPane.showMessageDialog(this,"Nuevo usuario Ingresado");
        }else{
            JOptionPane.showMessageDialog(this,"El usuario no ha podido ingresarse, es probable que el nombre o gmail concuerde con uno ya ingresado o que haya error en la conexion","ERROR", JOptionPane.WARNING_MESSAGE);
        }
        JNombre.setText("Ingrese nombre");        
        JContraseña1.setText("Ingrese contraseña");
        JContraseña2.setText("Ingrese devuelta la contraseña");
        JGmail.setText("Ingrese el gmail");
        for (int i=0; i<4;i++){
            Bandera[i] = false;
        }
    }//GEN-LAST:event_Envio_dataActionPerformed

    

                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Envio_data;
    private javax.swing.JTextField JContraseña1;
    private javax.swing.JTextField JContraseña2;
    private javax.swing.JTextField JGmail;
    private javax.swing.JTextField JNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
