/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestionar_Paquete.Ingresar_t;

import java.sql.Connection;
import Main_paquete.Bdd;
import javax.swing.JOptionPane;
import Gestionar_Paquete.Main_Gestionar;
/**
 *
 * @author HP OMEN
 */
public class Ingresar_tarjeta extends javax.swing.JFrame {
    boolean[] Bandera=new boolean[3];
    static Connection  conexion = null;
    static int id;
    Bdd bdd = new Bdd();
    public Ingresar_tarjeta(Connection conexion,int id) {
        initComponents();
        Ingresar_tarjeta.conexion=conexion;
        Ingresar_tarjeta.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JNumero = new javax.swing.JTextField();
        JFecha = new javax.swing.JTextField();
        JNum_seguridad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar informacion de tarjeta");

        JNumero.setText("Ingrese numero de tarjeta");
        JNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JNumeroFocusLost(evt);
            }
        });

        JFecha.setText("Ingrese la fecha de vencimiento");
        JFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JFechaFocusLost(evt);
            }
        });

        JNum_seguridad.setText("Ingrese el numero de seguridad");
        JNum_seguridad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JNum_seguridadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JNum_seguridadFocusLost(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JNum_seguridad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(JFecha, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(JNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(109, 109, 109)
                .addComponent(JNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(JFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(JNum_seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JNumeroFocusGained
        if (!Bandera[0]) {
            JNumero.setText("");
            Bandera[0] = true;
        }
    }//GEN-LAST:event_JNumeroFocusGained

    private void JNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JNumeroFocusLost
        if(JNumero.getText().isEmpty()){
            JNumero.setText("Ingrese numero de tarjeta");
            Bandera[0] = false;
        }
    }//GEN-LAST:event_JNumeroFocusLost

    private void JFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JFechaFocusGained
        if (!Bandera[1]) {
            JFecha.setText("");
            Bandera[1] = true;
        }
    }//GEN-LAST:event_JFechaFocusGained

    private void JFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JFechaFocusLost
        if(JFecha.getText().isEmpty()){
            JFecha.setText("Ingrese la fecha de vencimiento");
            Bandera[1] = false;
        }
    }//GEN-LAST:event_JFechaFocusLost

    private void JNum_seguridadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JNum_seguridadFocusGained
        if (!Bandera[2]) {
            JNum_seguridad.setText("");
            Bandera[2] = true;
        }
    }//GEN-LAST:event_JNum_seguridadFocusGained

    private void JNum_seguridadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JNum_seguridadFocusLost
        if(JNum_seguridad.getText().isEmpty()){
            JNum_seguridad.setText("Ingrese el numero de seguridad");
            Bandera[2] = false;
        }
    }//GEN-LAST:event_JNum_seguridadFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Num=Integer.parseInt(JNumero.getText());
        int Fecha=Integer.parseInt(JNumero.getText());
        int Num_seguridad=Integer.parseInt(JNumero.getText());
        
        if(bdd.insert_tarjeta(Num,Fecha,Num_seguridad,id,conexion)){
            JOptionPane.showMessageDialog(this,"Tarjeta creada");
            Main_Gestionar Mu=new Main_Gestionar(conexion,id);
            this.setVisible(false);
            Mu.setVisible(true);
            Mu.setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(this,"La tarjeta no se pudo crear","ERROR", JOptionPane.WARNING_MESSAGE);
            JNum_seguridad.setText("");
            JNumero.setText("");
            JFecha.setText("");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_tarjeta(conexion,id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JFecha;
    private javax.swing.JTextField JNum_seguridad;
    private javax.swing.JTextField JNumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
